import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { QrCode, ArrowLeft } from 'lucide-react';
import { Scanner } from '@yudiel/react-qr-scanner';

export default function ScanPage() {
  const navigate = useNavigate();
  const [error, setError] = useState<string | null>(null);

  const handleScan = (results: { rawValue: string }[]) => {
    if (!results || results.length === 0) return;
    const text = results[0].rawValue;

    try {
      // If QR contains a full URL (our current behavior), just navigate there.
      if (text.startsWith('http://') || text.startsWith('https://')) {
        window.location.href = text;
        return;
      }

      // Fallback: if it looks like a JSON payload, route into /pay using payload param.
      const parsed = JSON.parse(text);
      if (parsed && typeof parsed === 'object') {
        const payload = encodeURIComponent(JSON.stringify(parsed));
        navigate(`/pay?payload=${payload}`);
      } else {
        setError('Unsupported QR content');
      }
    } catch {
      setError('Could not read QR code');
    }
  };

  return (
    <main className="min-h-[calc(100vh-5rem)] flex items-center justify-center px-4 py-8 sm:px-6">
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.35 }}
        className="w-full max-w-md"
      >
        <div className="bg-secondary rounded-2xl border border-white/10 shadow-card-dark p-5 space-y-4">
          <div className="flex items-center justify-between text-xs">
            <button
              type="button"
              onClick={() => navigate(-1)}
              className="inline-flex items-center gap-1.5 text-secondary hover:text-primary"
            >
              <ArrowLeft className="w-3 h-3" />
              Back
            </button>
            <span className="text-secondary/80">Pay to an address</span>
          </div>

          <div className="flex items-center gap-3 mt-1">
            <div className="w-9 h-9 rounded-full bg-accent-green/15 flex items-center justify-center">
              <QrCode className="w-5 h-5 text-accent-green" />
            </div>
            <div>
              <h1 className="text-lg sm:text-xl font-semibold text-primary">Scan QR to pay</h1>
              <p className="text-xs text-secondary">Point your camera at a Payecho QR code.</p>
            </div>
          </div>

          <div className="mt-4 rounded-xl border border-white/15 bg-tertiary/60 overflow-hidden">
            <div className="aspect-square w-full bg-black/70 flex items-center justify-center">
              <Scanner
                onScan={(codes) => handleScan(codes as { rawValue: string }[])}
                onError={(error: unknown) =>
                  setError(error && typeof (error as any).message === 'string' ? (error as any).message : 'Camera error')
                }
                constraints={{
                  facingMode: 'environment',
                }}
              />
            </div>
          </div>

          {error && <p className="text-[11px] text-red-400 mt-2">{error}</p>}

          <p className="text-[11px] text-secondary mt-2">
            We only read QR codes generated by Payecho. When a valid code is scanned, you&apos;ll be redirected to the
            secure payment screen.
          </p>
        </div>
      </motion.div>
    </main>
  );
}

